// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxyvrigahplujprkvqay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4eXZyaWdhaHBsdWpwcmt2cWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTc3MDAsImV4cCI6MjA2NTk5MzcwMH0.V---5bOLUyA6W34JCczBgSNfeOZ2bZ0o0pwnicqXgOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);